version: '3.8'

services:
  postgresql-master:
      image: 'bitnami/postgresql:latest'
      ports:
        - '5432'
      environment:
        - POSTGRESQL_USERNAME=user
        - POSTGRESQL_PASSWORD=user
        - POSTGRESQL_DATABASE=tarea1
      volumes:
        - ../postgres/schema.sql:/docker-entrypoint-initdb.d/create_schema.sql

  redis-master:
    image: 'bitnami/redis:7.0.4-debian-11-r23'
    expose:
      - '6379'
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=master1234

  redis-replica-uno:
    image: 'bitnami/redis:7.0.4-debian-11-r23'
    expose:
      - '6379'
    depends_on:
      - redis-master
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_PASSWORD=master1234
      - REDIS_PASSWORD=replica1234

  redis-replica-dos:
    image: 'bitnami/redis:7.0.4-debian-11-r23'
    expose:
      - '6379'
    depends_on:
      - redis-master
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_PASSWORD=master1234
      - REDIS_PASSWORD=replica1234